### ISSUE TITLE
Allow the user to set a minimum and maximum character limit

### ISSUE THREAD

**Issue by GMRobo** [JamesOsborn-SE/eat-poop-you-cat-android#17]
Basically title, I don't run into the limit in the drawing portion, but in the typing portion, the limit is hit often, sometimes less is more in the typing portion

More chance for misinterpretation

**Comment by JamesOsborn-SE** [comment]
How about using words as the unit to change?

**Comment by GMRobo** [comment]
Yeah, because the glory of the game your game is inspired by (telephone), is the confusion that's caused by a message being relayed x amount of times before, losing detail with each telling

**Comment by JamesOsborn-SE** [comment]
I think the comment from #47 make me lean towards characters again.
