### ISSUE TITLE
Add Fdroid description and short subtext to translatable strings

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#20]
The game is translatable. Great :D

But Fdroid's long and short descriptions are still stuck to english text, which would help understand the game if it was translated!
Is it possible to add this text to Weblate for translation ?

**Comment by JamesOsborn-SE** [comment]
I'll see what I can do.

**Comment by JamesOsborn-SE** [comment]
let me know if this works.
https://hosted.weblate.org/translate/eat-poop-you-cat-android/metadata/en/?q=

**Comment by Cwpute** [comment]
I had to go to ``EatPoopYouCat/metadata`` ([here](https://hosted.weblate.org/projects/eat-poop-you-cat-android/metadata/)) and create a translation for my own language by clicking the ``+`` icon, and it worked yes ! :)
I have access to the translatable strings for the title, short description, full description and privacy policy.

**Comment by Cwpute** [comment]
Translated for french 👍
i'll close this issue now
