### ISSUE TITLE
Make app name translatable

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#21]
I was thinking that maybe we could also have the game name be translatable. Since it's in english, and game heavily relies on writing text, i think it could deter some people from trying it.
Would that be possible ?

Alternatively… but that would ée a huge change… alternatively the title could be changed to something entirely different and more universal so it doesn't need to be translated.

**Comment by JamesOsborn-SE** [comment]
This is a hard one. I think translating the title would be a good first step but I don't know how that works on the stores so I'll need to do some digging.

**Comment by Cwpute** [comment]
Just yesterday when searching for this repo i stumbled upon at least one other implementation of this game that used the same name. With some more search now i can safely say this is a well known and generic name for that game, but only in english-speaking countries (i thought maybe it was a custom name).

For exemple here in France i had never heard about it, we use the name "Jeu de téléphone", "Téléphone arabe", and sometimes "la rumeur" or "le passe-parole".
There is a list of many names in many other languaqes available on the french wikipedia page for the game: https://fr.wikipedia.org/wiki/T%C3%A9l%C3%A9phone_arabe

Le 4 janvier 2024 05:56:19 GMT+01:00, James Osborn ***@***.***> a écrit :

**Comment by JamesOsborn-SE** [comment]
I'm kinda surprised that `broken telephone` is the common translation (from x -> French -> English) for most of the list.

**Comment by Cwpute** [comment]
Well, it seems fair enough to me! A broken telephone only partially transfers the original message, so it fits :)
Do you want to argue on the relevancy of Eat Poop Yoa Cat for its name in english or…? 😄

**Comment by JamesOsborn-SE** [comment]
the internet loves cats.. just sayin'

**Comment by JamesOsborn-SE** [comment]
App name is translatable as far as I can tell. I'm still not sure how much of a good idea it is.

**Comment by Cwpute** [comment]
Maybe the name should be translated as to always include the original name in some form or another.
I can see four ways to handle this:
1. the original name always appear upfront in its entirety, with a translated subtitle `Eat Poop You Cat: le jeu du téléphone`
2. shortened original name `EPYC: le jeu du téléphone`
3. translated name upfront with the original one after it, either in full `Téléphone Cassé (Eat Poop You Cat)`
4. …or shortened `Téléphone Cassé (EPYC)`

**Comment by JamesOsborn-SE** [comment]
I think I like 3 the best
