### ISSUE TITLE
Include confidential policy directly in the app

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#24]
Seems strange to have your Cofnfidential Policy be a link to a website outside the app.

Couldn't they be included in the app directly ?

**Comment by JamesOsborn-SE** [comment]
How about a short blurb like "no data is shared" or something.. I'm afraid to change the link as it may upset the google. But I guess it would be easier to translate if it was in the app.

**Comment by Cwpute** [comment]
That would work yes.
As for Google, i don't remember seeing much apps use a link to their Privacy Policy, or even having one to link there… is it mandatory for Google Play Store ?

Le 4 janvier 2024 06:03:09 GMT+01:00, James Osborn ***@***.***> a écrit :

**Comment by Cwpute** [comment]
I've seen the privacy policy was added in the metadata strings of the app, so this might be a good time to close the issue ?

**Comment by JamesOsborn-SE** [comment]
It's been in the metadata for a while. I'm working on having the app read from that file. I'll close it when it's done.
