### ISSUE TITLE
Players don't always push "Submit"

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#28]
I've played several games now, with people of different profiles, and have found a good chunk of them either forgot or didn't understand they had to push the "Submit" button once they had finished their contribution.

Several suggestions to make it more obvious:

1. The current text `Submit` is a bit ambiguous, as the button uses a symbol similar to that of a paper plane, that is most used for sending messages over sms or internet (which is not the case here). I'd suggest to change the text to `Next!` and/or the symbol to something less ambiguous like this ⏩ or a tick ✅.
2. Make the button and its text bigger
3. Make the button take up the whole lenght at the bottom of the screen. Perhaps reserve some space for a burger menu button or three-dots menu (≡ or ⋯) for ending the whole game or accessing options in the future maybe.
4. Explicit what is happening in the game's instructiwns: `"The previous player wrote/drew…"` for what just happened and `"Describe what you see/Draw what is described for the next player"` for what is happening right now.

**Comment by JamesOsborn-SE** [comment]
I should do some A/B testing. I should not have used "Submit" according to the UX class I'm taking. I like `Next!`

I need to add a menu sooner or later for future features. I like the idea of hiding the end game there.

**Comment by JamesOsborn-SE** [comment]
Should be resolved in this release:
https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/releases/tag/v1.1.0
It may take some time to get to the stores. 
Feel free to reopen
