### ISSUE TITLE
Start a new game from a previous prompt/drawing

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#30]
When starting a game, i'd appreciate being able to select a prompt or drawing from a previously finished game, either at random or by choice.
That would help find a funny starting point when you can't think of any. It would also create funny ways to connect people asking about previous games !

**Comment by Cwpute** [comment]
If this suggestion was implemented, it would solve my other request in issue #22

**Comment by JamesOsborn-SE** [comment]
Thanks for the suggestion.

This feature has been added to v1.2.1
