### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [JamesOsborn-SE/eat-poop-you-cat-android#39]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6602483772#L1114

will get a diff soon

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/ac7702c5460784d9f9fa148f371dd75fa161c5f2

**Comment by JamesOsborn-SE** [comment]
Thanks for letting me know.

I'm sure it's related to commit f24ea11
I think I just need to put out a new Tag/release and delete 1.3.0

**Comment by JamesOsborn-SE** [comment]
Should be good now:
https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/releases/tag/v1.3.2

Thanks again and keep up the good work.

Feel free to reopen if it's still borked.

**Comment by licaon-kter** [comment]
https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/releases/tag/v1.4.6 has no APK?

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7405977910

**Comment by JamesOsborn-SE** [comment]
Crap, thanks for letting me know. I blame the French language.

**Comment by JamesOsborn-SE** [comment]
If I delete the tag and make some commits and make a new tag, will that mess up F-Droid build?

**Comment by licaon-kter** [comment]
@JamesOsborn-SE i just let it be so you just put the APK and things works out

If you want to tag a new release, then we need to adapt to that (remove old block etc)

**Comment by JamesOsborn-SE** [comment]
I'll just make a new version to keep it simple.
