### ISSUE TITLE
Shrink items on screen for foldable

### ISSUE THREAD

**Issue by Anti-Apple4life** [JamesOsborn-SE/eat-poop-you-cat-android#42]
When using the app on the main screen of a Galaxy Z Fold 5, parts of the UI get cut off, making the game more annoying to play. Images are attached below:

## Vertical
![Screenshot_20240415_182153_Eat Poop You Cat](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/59315931/0b63665c-e89c-46d3-b600-65d6c0c71715)
![Screenshot_20240415_182312_Eat Poop You Cat](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/59315931/10c0fc5d-01d2-47d9-95f7-98ec24e5bd06)
## Horizontal
![Screenshot_20240415_182201_Eat Poop You Cat](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/59315931/66628d8e-5df5-4a61-9140-910f7f87fe26)
![Screenshot_20240415_182317_Eat Poop You Cat](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/59315931/56e8de08-d845-4628-b65d-4964a7b86cdb)

**Comment by JamesOsborn-SE** [comment]
oof... I'll look into this. Thanks for the info

**Comment by JamesOsborn-SE** [comment]
I found a solution, but it may cause a different issue… I think this is an abuse case though
![image](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/3580335/7149b258-c6d6-4796-994a-2599460ef44f)

**Comment by JamesOsborn-SE** [comment]
what it should look like on an unfolded phone
![image](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/3580335/0f114f16-8be7-4154-8ceb-62e19801d80b)

**Comment by Anti-Apple4life** [comment]
https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/59315931/c8f31582-98c6-47e2-9963-c799380b9e3f

I installed the new update. There is now a different issue that (somewhat) fixes when rotating my phone.

**Comment by JamesOsborn-SE** [comment]
Good news! I was able to reproduce it in the emulator, so you don't have to lend me your phone.

**Comment by JamesOsborn-SE** [comment]
Check out the latest release.
https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/releases/tag/v1.4.5

 I was doing a bad and trying to calculate the size of the component by hand instead of using the right compose widget.
