### ISSUE TITLE
Community translations ?

### ISSUE THREAD

**Issue by Cwpute** [JamesOsborn-SE/eat-poop-you-cat-android#9]
Hi, i'd love to play this game with non-english speaking friends :) any chance you might set up a community translations project via [Weblate](https://weblate.org/) ? open-source projects get free hosting there.

Alternatively —and i think this could work— you could have most rules and buttons featuring drawings or symbols instead of text.

**Comment by JamesOsborn-SE** [comment]
I'm looking into Weblate. I think words are needed to keep actions unambiguous but I could do both.

**Comment by JamesOsborn-SE** [comment]
@NicoleYOsborn 
How do you feel about these buttons?

![image](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/3580335/ddfb1593-c4ef-42af-8498-8877efe9fa69)
![image](https://github.com/JamesOsborn-SE/eat-poop-you-cat-android/assets/3580335/8ca5eae7-3362-406f-bec9-cd0a36873164)

**Comment by JamesOsborn-SE** [comment]
Added icons in v1.0.4 I  hope this helps but I'm still working on the community translations

**Comment by Cwpute** [comment]
> How do you feel about these buttons?

It's great ! however, i'd use the is emoji 🏁 for starting a game

**Comment by JamesOsborn-SE** [comment]
Checkered flag  🏁 means the end in racing. So that might be good for end game for all. There may be different meanings for flags in other cultures I don't know about. 
https://en.wikipedia.org/wiki/Racing_flags

**Comment by Jerome-Herbinet** [comment]
I'm taking care of French translation.

**Comment by JamesOsborn-SE** [comment]
Libre hosting is Pending approval. I think once that's approved I can push the translations to this repo/get automatic updates

**Comment by JamesOsborn-SE** [comment]
Would it be bad form to manually add the translations? I'm still waiting for approval. You folks could put in PRs as well.

**Comment by Jerome-Herbinet** [comment]
I think I'll finish translation (French) on Wednesday.

**Comment by JamesOsborn-SE** [comment]
I'm closing this. I figured out how to work Weblate and added the status to the readme.

I really appreciate you folks helping to translate and I hope you enjoy the game.
